export const countryList = [
  { name: "Afghanistan", code: "AF", cost: 4 },
  { name: "land Islands", code: "AX", cost: 6 },
  { name: "Albania", code: "AL", cost: 6 },
  { name: "Algeria", code: "DZ", cost: 6 },
  { name: "American Samoa", code: "AS", cost: 6 },
  { name: "AndorrA", code: "AD", cost: 6 },
  { name: "Angola", code: "AO", cost: 6 },
  { name: "Anguilla", code: "AI", cost: 6 },
  { name: "Antarctica", code: "AQ", cost: 6 },
  { name: "Antigua and Barbuda", code: "AG", cost: 6 },
  { name: "Argentina", code: "AR", cost: 6 },
  { name: "Armenia", code: "AM", cost: 6 },
  { name: "Aruba", code: "AW", cost: 6 },
  { name: "Australia", code: "AU", cost: 6 },
  { name: "Austria", code: "AT", cost: 6 },
  { name: "Azerbaijan", code: "AZ", cost: 6 },
  { name: "Bahamas", code: "BS", cost: 6 },
  { name: "Bahrain", code: "BH", cost: 6 },
  { name: "Bangladesh", code: "BD", cost: 6 },
  { name: "Barbados", code: "BB", cost: 6 },
  { name: "Belarus", code: "BY", cost: 6 },
  { name: "Belgium", code: "BE", cost: 6 },
  { name: "Belize", code: "BZ", cost: 6 },
  { name: "Benin", code: "BJ", cost: 6 },
  { name: "Bermuda", code: "BM", cost: 6 },
  { name: "Bhutan", code: "BT", cost: 6 },
  { name: "Bolivia", code: "BO", cost: 6 },
  { name: "Bosnia and Herzegovina", code: "BA", cost: 6 },
  { name: "Botswana", code: "BW", cost: 6 },
  { name: "Bouvet Island", code: "BV", cost: 6 },
  { name: "Brazil", code: "BR", cost: 6 },
  { name: "British Indian Ocean Territory", code: "IO", cost: 6 },
  { name: "Brunei Darussalam", code: "BN", cost: 6 },
  { name: "Bulgaria", code: "BG", cost: 6 },
  { name: "Burkina Faso", code: "BF", cost: 6 },
  { name: "Burundi", code: "BI", cost: 6 },
  { name: "Cambodia", code: "KH", cost: 6 },
  { name: "Cameroon", code: "CM", cost: 6 },
  { name: "Canada", code: "CA", cost: 6 },
  { name: "Cape Verde", code: "CV", cost: 6 },
  { name: "Cayman Islands", code: "KY", cost: 6 },
  { name: "Central African Republic", code: "CF", cost: 6 },
  { name: "Chad", code: "TD", cost: 6 },
  { name: "Chile", code: "CL", cost: 6 },
  { name: "China", code: "CN", cost: 6 },
  { name: "Christmas Island", code: "CX", cost: 6 },
  { name: "Cocos (Keeling) Islands", code: "CC", cost: 6 },
  { name: "Colombia", code: "CO", cost: 6 },
  { name: "Comoros", code: "KM", cost: 6 },
  { name: "Congo", code: "CG", cost: 6 },
  { name: "Congo, The Democratic Republic of the", code: "CD", cost: 6 },
  { name: "Cook Islands", code: "CK", cost: 6 },
  { name: "Costa Rica", code: "CR", cost: 6 },
  { name: "Cote D'ivoire", code: "CI", cost: 6 },
  { name: "Croatia", code: "HR", cost: 6 },
  { name: "Cuba", code: "CU", cost: 6 },
  { name: "Cyprus", code: "CY", cost: 6 },
  { name: "Czech Republic", code: "CZ", cost: 6 },
  { name: "Denmark", code: "DK", cost: 6 },
  { name: "Djibouti", code: "DJ", cost: 6 },
  { name: "Dominica", code: "DM", cost: 6 },
  { name: "Dominican Republic", code: "DO", cost: 6 },
  { name: "Ecuador", code: "EC", cost: 6 },
  { name: "Egypt", code: "EG", cost: 6 },
  { name: "El Salvador", code: "SV", cost: 6 },
  { name: "Equatorial Guinea", code: "GQ", cost: 6 },
  { name: "Eritrea", code: "ER", cost: 6 },
  { name: "Estonia", code: "EE", cost: 6 },
  { name: "Ethiopia", code: "ET", cost: 6 },
  { name: "Falkland Islands (Malvinas)", code: "FK", cost: 6 },
  { name: "Faroe Islands", code: "FO", cost: 6 },
  { name: "Fiji", code: "FJ", cost: 6 },
  { name: "Finland", code: "FI", cost: 6 },
  { name: "France", code: "FR", cost: 6 },
  { name: "French Guiana", code: "GF", cost: 6 },
  { name: "French Polynesia", code: "PF", cost: 6 },
  { name: "French Southern Territories", code: "TF", cost: 6 },
  { name: "Gabon", code: "GA", cost: 6 },
  { name: "Gambia", code: "GM", cost: 6 },
  { name: "Georgia", code: "GE", cost: 6 },
  { name: "Germany", code: "DE", cost: 5 },
  { name: "Ghana", code: "GH", cost: 6 },
  { name: "Gibraltar", code: "GI", cost: 6 },
  { name: "Greece", code: "GR", cost: 6 },
  { name: "Greenland", code: "GL", cost: 6 },
  { name: "Grenada", code: "GD", cost: 6 },
  { name: "Guadeloupe", code: "GP", cost: 6 },
  { name: "Guam", code: "GU", cost: 6 },
  { name: "Guatemala", code: "GT", cost: 6 },
  { name: "Guernsey", code: "GG", cost: 6 },
  { name: "Guinea", code: "GN", cost: 6 },
  { name: "Guinea-Bissau", code: "GW", cost: 6 },
  { name: "Guyana", code: "GY", cost: 6 },
  { name: "Haiti", code: "HT", cost: 6 },
  { name: "Heard Island and Mcdonald Islands", code: "HM", cost: 6 },
  { name: "Holy See (Vatican City State)", code: "VA", cost: 6 },
  { name: "Honduras", code: "HN", cost: 6 },
  { name: "Hong Kong", code: "HK", cost: 6 },
  { name: "Hungary", code: "HU", cost: 6 },
  { name: "Iceland", code: "IS", cost: 6 },
  { name: "India", code: "IN", cost: 6 },
  { name: "Indonesia", code: "ID", cost: 6 },
  { name: "Iran, Islamic Republic Of", code: "IR", cost: 6 },
  { name: "Iraq", code: "IQ", cost: 6 },
  { name: "Ireland", code: "IE", cost: 6 },
  { name: "Isle of Man", code: "IM", cost: 6 },
  { name: "Israel", code: "IL", cost: 6 },
  { name: "Italy", code: "IT", cost: 7 },
  { name: "Jamaica", code: "JM", cost: 6 },
  { name: "Japan", code: "JP", cost: 6 },
  { name: "Jersey", code: "JE", cost: 6 },
  { name: "Jordan", code: "JO", cost: 6 },
  { name: "Kazakhstan", code: "KZ", cost: 6 },
  { name: "Kenya", code: "KE", cost: 6 },
  { name: "Kiribati", code: "KI", cost: 6 },
  { name: "Korea, Democratic People's Republic of", code: "KP", cost: 6 },
  { name: "Korea, Republic of", code: "KR", cost: 6 },
  { name: "Kuwait", code: "KW", cost: 6 },
  { name: "Kyrgyzstan", code: "KG", cost: 6 },
  { name: "Lao People's Democratic Republic", code: "LA", cost: 6 },
  { name: "Latvia", code: "LV", cost: 6 },
  { name: "Lebanon", code: "LB", cost: 6 },
  { name: "Lesotho", code: "LS", cost: 6 },
  { name: "Liberia", code: "LR", cost: 6 },
  { name: "Libyan Arab Jamahiriya", code: "LY", cost: 6 },
  { name: "Liechtenstein", code: "LI", cost: 6 },
  { name: "Lithuania", code: "LT", cost: 6 },
  { name: "Luxembourg", code: "LU", cost: 6 },
  { name: "Macao", code: "MO", cost: 6 },
  {
    name: "Macedonia, The Former Yugoslav Republic of",
    code: "MK",
    cost: 6,
  },
  { name: "Madagascar", code: "MG", cost: 6 },
  { name: "Malawi", code: "MW", cost: 6 },
  { name: "Malaysia", code: "MY", cost: 6 },
  { name: "Maldives", code: "MV", cost: 6 },
  { name: "Mali", code: "ML", cost: 6 },
  { name: "Malta", code: "MT", cost: 6 },
  { name: "Marshall Islands", code: "MH", cost: 6 },
  { name: "Martinique", code: "MQ", cost: 6 },
  { name: "Mauritania", code: "MR", cost: 6 },
  { name: "Mauritius", code: "MU", cost: 6 },
  { name: "Mayotte", code: "YT", cost: 6 },
  { name: "Mexico", code: "MX", cost: 6 },
  { name: "Micronesia, Federated States of", code: "FM", cost: 6 },
  { name: "Moldova, Republic of", code: "MD", cost: 6 },
  { name: "Monaco", code: "MC", cost: 6 },
  { name: "Mongolia", code: "MN", cost: 6 },
  { name: "Montenegro", code: "ME", cost: 6 },
  { name: "Montserrat", code: "MS", cost: 6 },
  { name: "Morocco", code: "MA", cost: 6 },
  { name: "Mozambique", code: "MZ", cost: 6 },
  { name: "Myanmar", code: "MM", cost: 6 },
  { name: "Namibia", code: "NA", cost: 6 },
  { name: "Nauru", code: "NR", cost: 6 },
  { name: "Nepal", code: "NP", cost: 6 },
  { name: "Netherlands", code: "NL", cost: 10 },
  { name: "Netherlands Antilles", code: "AN", cost: 6 },
  { name: "New Caledonia", code: "NC", cost: 6 },
  { name: "New Zealand", code: "NZ", cost: 6 },
  { name: "Nicaragua", code: "NI", cost: 6 },
  { name: "Niger", code: "NE", cost: 6 },
  { name: "Nigeria", code: "NG", cost: 6 },
  { name: "Niue", code: "NU", cost: 6 },
  { name: "Norfolk Island", code: "NF", cost: 6 },
  { name: "Northern Mariana Islands", code: "MP", cost: 6 },
  { name: "Norway", code: "NO", cost: 6 },
  { name: "Oman", code: "OM", cost: 6 },
  { name: "Pakistan", code: "PK", cost: 6 },
  { name: "Palau", code: "PW", cost: 6 },
  { name: "Palestinian Territory, Occupied", code: "PS", cost: 6 },
  { name: "Panama", code: "PA", cost: 6 },
  { name: "Papua New Guinea", code: "PG", cost: 6 },
  { name: "Paraguay", code: "PY", cost: 6 },
  { name: "Peru", code: "PE", cost: 6 },
  { name: "Philippines", code: "PH", cost: 6 },
  { name: "Pitcairn", code: "PN", cost: 6 },
  { name: "Poland", code: "PL", cost: 6 },
  { name: "Portugal", code: "PT", cost: 6 },
  { name: "Puerto Rico", code: "PR", cost: 6 },
  { name: "Qatar", code: "QA", cost: 6 },
  { name: "Reunion", code: "RE", cost: 6 },
  { name: "Romania", code: "RO", cost: 6 },
  { name: "Russian Federation", code: "RU", cost: 6 },
  { name: "RWANDA", code: "RW", cost: 6 },
  { name: "Saint Helena", code: "SH", cost: 6 },
  { name: "Saint Kitts and Nevis", code: "KN", cost: 6 },
  { name: "Saint Lucia", code: "LC", cost: 6 },
  { name: "Saint Pierre and Miquelon", code: "PM", cost: 6 },
  { name: "Saint Vincent and the Grenadines", code: "VC", cost: 6 },
  { name: "Samoa", code: "WS", cost: 6 },
  { name: "San Marino", code: "SM", cost: 6 },
  { name: "Sao Tome and Principe", code: "ST", cost: 6 },
  { name: "Saudi Arabia", code: "SA", cost: 6 },
  { name: "Senegal", code: "SN", cost: 6 },
  { name: "Serbia", code: "RS", cost: 6 },
  { name: "Seychelles", code: "SC", cost: 6 },
  { name: "Sierra Leone", code: "SL", cost: 6 },
  { name: "Singapore", code: "SG", cost: 6 },
  { name: "Slovakia", code: "SK", cost: 6 },
  { name: "Slovenia", code: "SI", cost: 6 },
  { name: "Solomon Islands", code: "SB", cost: 6 },
  { name: "Somalia", code: "SO", cost: 6 },
  { name: "South Africa", code: "ZA", cost: 6 },
  {
    name: "South Georgia and the South Sandwich Islands",
    code: "GS",
    cost: 6,
  },
  { name: "Spain", code: "ES", cost: 6 },
  { name: "Sri Lanka", code: "LK", cost: 6 },
  { name: "Sudan", code: "SD", cost: 6 },
  { name: "Suriname", code: "SR", cost: 6 },
  { name: "Svalbard and Jan Mayen", code: "SJ", cost: 6 },
  { name: "Swaziland", code: "SZ", cost: 6 },
  { name: "Sweden", code: "SE", cost: 6 },
  { name: "Switzerland", code: "CH", cost: 6 },
  { name: "Syrian Arab Republic", code: "SY", cost: 6 },
  { name: "Taiwan, Province of China", code: "TW", cost: 6 },
  { name: "Tajikistan", code: "TJ", cost: 6 },
  { name: "Tanzania, United Republic of", code: "TZ", cost: 6 },
  { name: "Thailand", code: "TH", cost: 6 },
  { name: "Timor-Leste", code: "TL", cost: 6 },
  { name: "Togo", code: "TG", cost: 6 },
  { name: "Tokelau", code: "TK", cost: 6 },
  { name: "Tonga", code: "TO", cost: 6 },
  { name: "Trinidad and Tobago", code: "TT", cost: 6 },
  { name: "Tunisia", code: "TN", cost: 6 },
  { name: "Turkey", code: "TR", cost: 6 },
  { name: "Turkmenistan", code: "TM", cost: 6 },
  { name: "Turks and Caicos Islands", code: "TC", cost: 6 },
  { name: "Tuvalu", code: "TV", cost: 6 },
  { name: "Uganda", code: "UG", cost: 6 },
  { name: "Ukraine", code: "UA", cost: 6 },
  { name: "United Arab Emirates", code: "AE", cost: 6 },
  { name: "United Kingdom", code: "GB", cost: 6 },
  { name: "United States", code: "US", cost: 6 },
  { name: "United States Minor Outlying Islands", code: "UM", cost: 6 },
  { name: "Uruguay", code: "UY", cost: 6 },
  { name: "Uzbekistan", code: "UZ", cost: 6 },
  { name: "Vanuatu", code: "VU", cost: 6 },
  { name: "Venezuela", code: "VE", cost: 6 },
  { name: "Viet Nam", code: "VN", cost: 6 },
  { name: "Virgin Islands, British", code: "VG", cost: 6 },
  { name: "Virgin Islands, U.S.", code: "VI", cost: 6 },
  { name: "Wallis and Futuna", code: "WF", cost: 6 },
  { name: "Western Sahara", code: "EH", cost: 6 },
  { name: "Yemen", code: "YE", cost: 6 },
  { name: "Zambia", code: "ZM", cost: 6 },
  { name: "Zimbabwe", code: "ZW", cost: 6 },
];
